import type { DocumentationSection } from './DocumentationPanel.vue';

export const systemDocumentationSections: DocumentationSection[] = [
    {
        key: 'general',
        title: 'Allgemeine Beschreibung',
        description: 'Zweck, fachliche und technische Einordnung.',
        fields: [
            { key: 'purpose', label: 'Zweck', type: 'textarea', required: true },
            { key: 'business_significance', label: 'Fachliche Bedeutung', type: 'textarea', required: true },
            { key: 'technical_description', label: 'Technische Beschreibung', type: 'textarea', required: true },
            { key: 'special_notes', label: 'Besonderheiten', type: 'textarea' },
        ],
    },
    {
        key: 'product_support',
        title: 'Produkt und Hersteller',
        description: 'Portale, Support und Vertragsinformationen ergänzend zu den Stammdaten.',
        fields: [
            { key: 'vendor_portal', label: 'Herstellerportal', type: 'url' },
            { key: 'documentation_url', label: 'Dokumentationslink', type: 'url' },
            { key: 'support_contact', label: 'Supportkontakt', required: true },
            { key: 'support_contract', label: 'Supportvertrag' },
            { key: 'contract_number', label: 'Vertragsnummer' },
            { key: 'support_hours', label: 'Supportzeiten' },
        ],
    },
    {
        key: 'responsibilities',
        title: 'Verantwortlichkeiten',
        description: 'Interne, externe, technische und fachliche Zuständigkeiten.',
        fields: [
            { key: 'technical_owner', label: 'Technischer Verantwortlicher', required: true },
            { key: 'business_owner', label: 'Fachlicher Verantwortlicher', required: true },
            { key: 'deputy', label: 'Vertretung' },
            { key: 'internal_contacts', label: 'Interne Ansprechpartner', type: 'textarea' },
            { key: 'external_contacts', label: 'Externe Ansprechpartner', type: 'textarea' },
        ],
    },
    {
        key: 'operations',
        title: 'Betrieb',
        description: 'Betriebszeiten, Wartung, Abhängigkeiten und Einschränkungen.',
        fields: [
            { key: 'operational_status', label: 'Betriebsstatus', required: true },
            { key: 'operating_hours', label: 'Betriebszeiten', required: true },
            { key: 'maintenance_window', label: 'Wartungsfenster', required: true },
            { key: 'planned_maintenance', label: 'Geplante Wartung', type: 'textarea' },
            { key: 'dependencies', label: 'Abhängigkeiten', type: 'textarea' },
            { key: 'known_limitations', label: 'Bekannte Einschränkungen', type: 'textarea' },
        ],
    },
    {
        key: 'network',
        title: 'Netzwerk',
        description: 'Zusätzliche Netzwerk-, Firewall- und Zertifikatshinweise.',
        fields: [
            { key: 'vlan', label: 'VLAN' },
            { key: 'firewall_notes', label: 'Firewallhinweise', type: 'textarea', required: true },
            { key: 'required_ports', label: 'Benötigte Ports', type: 'textarea', required: true },
            { key: 'proxy', label: 'Proxy' },
            { key: 'tls_notes', label: 'TLS' },
            { key: 'certificate_information', label: 'Zertifikatsinformationen', type: 'textarea' },
        ],
    },
    {
        key: 'interfaces',
        title: 'Schnittstellen',
        description: 'DICOM, HL7, FHIR, LDAP, REST und weitere Integrationen.',
        fields: [
            { key: 'dicom', label: 'DICOM', type: 'textarea' },
            { key: 'hl7', label: 'HL7', type: 'textarea' },
            { key: 'fhir', label: 'FHIR', type: 'textarea' },
            { key: 'ldap', label: 'LDAP', type: 'textarea' },
            { key: 'rest', label: 'REST', type: 'textarea' },
            { key: 'database', label: 'Datenbank', type: 'textarea' },
            { key: 'file_interfaces', label: 'Dateischnittstellen', type: 'textarea' },
            { key: 'other_interfaces', label: 'Sonstige Schnittstellen', type: 'textarea' },
        ],
    },
    {
        key: 'backup_recovery',
        title: 'Backup und Wiederherstellung',
        description: 'Sicherung, Aufbewahrung und Wiederherstellungsziele.',
        fields: [
            { key: 'backup_strategy', label: 'Backupstrategie', type: 'textarea', required: true },
            { key: 'backup_target', label: 'Sicherungsziel', required: true },
            { key: 'interval', label: 'Intervall', required: true },
            { key: 'retention', label: 'Aufbewahrung' },
            { key: 'recovery_procedure', label: 'Recovery-Verfahren', type: 'textarea', required: true },
            { key: 'rto', label: 'RTO' },
            { key: 'rpo', label: 'RPO' },
            { key: 'last_recovery_test', label: 'Letzter Wiederherstellungstest' },
        ],
    },
    {
        key: 'monitoring',
        title: 'Monitoring',
        description: 'Health Checks, Alarmierung und Eskalation.',
        fields: [
            { key: 'monitoring_present', label: 'Monitoring vorhanden', type: 'boolean', required: true },
            { key: 'monitoring_system', label: 'Monitoring-System' },
            { key: 'health_checks', label: 'Health Checks', type: 'textarea', required: true },
            { key: 'alerting', label: 'Alarmierung', type: 'textarea' },
            { key: 'recipients', label: 'Empfänger', type: 'textarea' },
            { key: 'escalation_path', label: 'Eskalationsweg', type: 'textarea' },
        ],
    },
    {
        key: 'emergency_restart',
        title: 'Notfall und Wiederanlauf',
        description: 'Notfallverfahren, Reihenfolge, Fallback und Kontaktkette.',
        fields: [
            { key: 'emergency_procedure', label: 'Notfallverfahren', type: 'textarea', required: true },
            { key: 'restart_order', label: 'Wiederanlaufreihenfolge', type: 'textarea', required: true },
            { key: 'dependencies', label: 'Abhängigkeiten', type: 'textarea' },
            { key: 'manual_fallback', label: 'Manueller Fallback', type: 'textarea', required: true },
            { key: 'contact_chain', label: 'Kontaktkette', type: 'textarea' },
        ],
    },
    {
        key: 'links_references',
        title: 'Links und Referenzen',
        description: 'Handbücher, Wiki, Ticketsystem und weitere Quellen.',
        fields: [
            { key: 'manuals', label: 'Handbücher', type: 'textarea' },
            { key: 'vendor_documentation', label: 'Herstellerdokumentation', type: 'textarea' },
            { key: 'internal_wikis', label: 'Interne Wikis', type: 'textarea' },
            { key: 'ticket_system', label: 'Ticketsystem', type: 'url' },
            { key: 'other_links', label: 'Weitere Links', type: 'textarea' },
        ],
    },
];
